server:
  port: 8711

eureka:
  client:
    serviceUrl:
          defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
      name: demo-config-client
  rabbitmq:
      host: peer1
      port: 5672
      username: admin
      password: admin123

